'use client';

import { useState } from 'react';
import { AlertTriangle, ChevronDown, ChevronUp, ExternalLink } from 'lucide-react';

interface AIDisclaimerProps {
  type: 'valuation' | 'legal' | 'financial' | 'underwriting' | 'general';
  /** If true, shows a compact inline banner instead of the full disclaimer */
  compact?: boolean;
  /** For legal docs (contracts, CIM) — requires user acknowledgment before action */
  requireAck?: boolean;
  ackLabel?: string;
  onAck?: () => void;
  className?: string;
}

const DISCLAIMER_CONTENT = {
  valuation: {
    title: 'AI-Generated Valuation — Not a Certified Appraisal',
    short: 'This valuation is generated by AI using publicly available methods and your submitted data. It is not a certified appraisal and should not be used as the sole basis for any financial decision.',
    full: [
      'This business valuation is produced by an AI system and is provided for informational and planning purposes only.',
      'It does not constitute a certified business appraisal, fairness opinion, or professional financial advice.',
      'Valuations may differ materially from what a licensed appraiser, business broker, or M&A advisor would determine after physical inspection, document review, and market analysis.',
      'Before relying on this valuation for any transaction, financing, litigation, tax, or estate planning purpose, you should engage a qualified, licensed business appraiser or CPA.',
      'Heradyne makes no representations or warranties regarding the accuracy or completeness of AI-generated valuations.',
    ],
  },
  legal: {
    title: 'AI-Generated Draft — Not Legal Advice',
    short: 'This document is an AI-generated draft for reference only. It is NOT a legally binding agreement and has NOT been reviewed by a licensed attorney.',
    full: [
      'This document was generated by an AI system based on the parameters you provided. It is a starting point draft only.',
      'This document has NOT been reviewed, approved, or prepared by a licensed attorney and does NOT constitute legal advice.',
      'Contracts, agreements, and legal documents have significant consequences. Before signing or relying on any AI-generated document, you MUST have it reviewed by a qualified attorney licensed in your jurisdiction.',
      'Heradyne expressly disclaims any liability arising from your use of AI-generated legal documents without independent legal review.',
      'Nothing in this platform creates an attorney-client relationship between Heradyne and any user.',
    ],
  },
  financial: {
    title: 'AI Analysis — Not Financial Advice',
    short: 'This analysis is generated by AI for informational purposes only. It is not financial advice and should not be the sole basis for any financial decision.',
    full: [
      'AI-generated financial analysis is provided for informational purposes only and does not constitute financial, investment, tax, or accounting advice.',
      'Past performance, historical benchmarks, and projected figures used in this analysis do not guarantee future results.',
      'Before making any financial decision based on this analysis, consult a qualified financial advisor, CPA, or investment professional.',
      'Heradyne is not a registered investment advisor, broker-dealer, or financial planner.',
    ],
  },
  underwriting: {
    title: 'AI Underwriting Score — Decision Support Only',
    short: 'This AI underwriting score is a decision support tool only. All final credit decisions must be made by a qualified human underwriter in accordance with applicable regulations.',
    full: [
      'AI underwriting outputs are decision support tools and do not constitute a credit decision, loan approval, or denial.',
      'All final credit decisions must be made by a qualified human loan officer or credit committee in compliance with ECOA, fair lending laws, and applicable SBA regulations.',
      'If a credit decision results in an adverse action, an ECOA-compliant adverse action notice must be provided to the applicant.',
      'Lenders are responsible for ensuring their use of AI decision support tools complies with applicable federal and state fair lending regulations, including disparate impact analysis.',
      'AI scores should be one input among many, not the determinative factor in any credit decision.',
    ],
  },
  general: {
    title: 'AI-Generated Content — For Informational Use Only',
    short: 'This content is generated by AI and is provided for informational purposes only. Verify important details independently before taking action.',
    full: [
      'AI-generated content is produced by a machine learning model and may contain errors, omissions, or inaccuracies.',
      'Always verify critical information independently, especially before making decisions involving legal, financial, medical, or other significant matters.',
      'Heradyne provides AI-generated content as a productivity tool, not as professional advice of any kind.',
    ],
  },
};

export function AIDisclaimer({ type, compact, requireAck, ackLabel, onAck, className }: AIDisclaimerProps) {
  const [expanded, setExpanded] = useState(false);
  const [acknowledged, setAcknowledged] = useState(false);
  const content = DISCLAIMER_CONTENT[type];

  if (compact) {
    return (
      <div className={`flex items-start gap-2 text-xs text-amber-800 bg-amber-50 border border-amber-200 rounded-lg px-3 py-2 ${className || ''}`}>
        <AlertTriangle className="h-3.5 w-3.5 text-amber-500 shrink-0 mt-0.5" />
        <span>{content.short}</span>
      </div>
    );
  }

  return (
    <div className={`border border-amber-300 bg-amber-50 rounded-xl overflow-hidden ${className || ''}`}>
      <button
        onClick={() => setExpanded(!expanded)}
        className="w-full flex items-start justify-between px-4 py-3 text-left hover:bg-amber-100 transition-colors"
      >
        <div className="flex items-center gap-2">
          <AlertTriangle className="h-4 w-4 text-amber-600 shrink-0" />
          <span className="text-sm font-semibold text-amber-800">{content.title}</span>
        </div>
        {expanded ? <ChevronUp className="h-4 w-4 text-amber-500 shrink-0" /> : <ChevronDown className="h-4 w-4 text-amber-500 shrink-0" />}
      </button>

      <div className="px-4 pb-1">
        <p className="text-xs text-amber-700">{content.short}</p>
      </div>

      {expanded && (
        <div className="px-4 pb-4 pt-2 border-t border-amber-200 mt-1 space-y-2">
          {content.full.map((para, i) => (
            <p key={i} className="text-xs text-amber-800 leading-relaxed">• {para}</p>
          ))}
        </div>
      )}

      {requireAck && !acknowledged && (
        <div className="px-4 pb-4 pt-2 border-t border-amber-200">
          <label className="flex items-start gap-2 cursor-pointer">
            <input
              type="checkbox"
              checked={acknowledged}
              onChange={e => {
                setAcknowledged(e.target.checked);
                if (e.target.checked && onAck) onAck();
              }}
              className="h-4 w-4 rounded border-amber-400 text-amber-600 mt-0.5 shrink-0"
            />
            <span className="text-xs text-amber-800 font-medium">
              {ackLabel || 'I understand this is an AI-generated draft and I will have it reviewed by a qualified professional before relying on it.'}
            </span>
          </label>
        </div>
      )}

      {requireAck && acknowledged && (
        <div className="px-4 pb-3 flex items-center gap-1 text-xs text-green-700">
          <span className="font-medium">✓ Acknowledged</span>
        </div>
      )}
    </div>
  );
}

/** Slim banner for inline use inside cards */
export function DisclaimerBanner({ text, className }: { text: string; className?: string }) {
  return (
    <div className={`flex items-start gap-2 text-xs text-gray-500 border-t border-gray-100 pt-2 mt-2 ${className || ''}`}>
      <AlertTriangle className="h-3 w-3 text-amber-400 shrink-0 mt-0.5" />
      <span>{text}</span>
    </div>
  );
}

/** Use at bottom of contract/CIM pages before the signature action */
export function LegalAckGate({
  onConfirm,
  disabled,
  actionLabel = 'Continue to Sign',
  children,
}: {
  onConfirm: () => void;
  disabled?: boolean;
  actionLabel?: string;
  children?: React.ReactNode;
}) {
  const [checked1, setChecked1] = useState(false);
  const [checked2, setChecked2] = useState(false);
  const canProceed = checked1 && checked2 && !disabled;

  return (
    <div className="bg-amber-50 border-2 border-amber-300 rounded-2xl p-5 space-y-4">
      <div className="flex items-center gap-2">
        <AlertTriangle className="h-5 w-5 text-amber-600 shrink-0" />
        <p className="font-semibold text-amber-900">Before You Sign</p>
      </div>

      <div className="space-y-3">
        <label className="flex items-start gap-3 cursor-pointer">
          <input type="checkbox" checked={checked1} onChange={e => setChecked1(e.target.checked)}
            className="h-4 w-4 rounded border-amber-400 text-amber-600 mt-0.5 shrink-0" />
          <span className="text-sm text-amber-800">
            I understand this is an AI-generated draft agreement and that Heradyne is not providing legal advice. I have read or will read this document in full before signing.
          </span>
        </label>
        <label className="flex items-start gap-3 cursor-pointer">
          <input type="checkbox" checked={checked2} onChange={e => setChecked2(e.target.checked)}
            className="h-4 w-4 rounded border-amber-400 text-amber-600 mt-0.5 shrink-0" />
          <span className="text-sm text-amber-800">
            I acknowledge that I should have this agreement reviewed by a qualified attorney before signing, and that my electronic signature indicates acceptance of the stated terms.
          </span>
        </label>
      </div>

      {children}

      <button
        onClick={onConfirm}
        disabled={!canProceed}
        className={`w-full py-3 rounded-xl font-semibold text-sm transition-all ${
          canProceed
            ? 'bg-blue-600 text-white hover:bg-blue-700 cursor-pointer'
            : 'bg-gray-200 text-gray-400 cursor-not-allowed'
        }`}
      >
        {actionLabel}
      </button>
      {!canProceed && <p className="text-xs text-amber-600 text-center">Check both boxes above to continue</p>}
    </div>
  );
}
